export const calendarOptions = {
	allDay: 'All day',
	previous: '< Prev',
	next: 'Next >',
	today: 'Today',
	month: 'Month',
	week: 'Week',
	day: 'Day',
	agenda: 'Diary',
	date: 'Date',
	time: 'Time',
	event: 'Event',
	noEventsInRange: 'There are no events in this range',
	showMore: (total) => `+ Show more (${total})`,
};
